### ISSUE TITLE
SchemeScript Github Wiki 

### ISSUE THREAD

**Issue by luserx0** [schemeway/SchemeScript#16]
Maybe we should create a wiki for the project.
Now now tho, just an idea for the future.
We gotta first make the readme perfect

**Comment by schemeway** [comment]
Not sure what a "perfect" README would look like...

**Comment by luserx0** [comment]
Haven't yet made the README "perfect" and probably we won't ever, cause "perfect" is subjective.

Closing this one.
//Still gotta add more content to the wiki
