### ISSUE TITLE
User Manual

### ISSUE THREAD

**Issue by luserx0** [schemeway/SchemeScript#17]
We should update the user manual a little.
Also we might want to upload it online (like the basis for our wiki) 
for people to see and get help

**Comment by schemeway** [comment]
I concur.  The user manual should be moved to the wiki, and the Help contents in the plugin could simply redirect the user to the wiki.

**Comment by luserx0** [comment]
Ported the user guide to github's wiki and added a sidebar. Also took care of the help contents to reflect the changes.
Have one problem with the editing page (https://github.com/angelozerr/angularjs-eclipse/wiki/_Sidebar/_edit) 

Gotta update the screenshots and test out the whole of manual to ensure that it has no faults.

**Comment by luserx0** [comment]
Ok the whole process is complete.
I wrote the whole Editing table by hand in Markdown. Ew : -1: 

Closing this one opening two smaller ones

**Comment by schemeway** [comment]
Nice jobs, Harry!
