### ISSUE TITLE
Instructions for how to install

### ISSUE THREAD

**Issue by misgeatgit** [schemeway/SchemeScript#9]
It would be nice to update the README file with a section dedicated to how to install this tool.

**Comment by schemeway** [comment]
Good point. Just did it!

**Comment by misgeatgit** [comment]
Thanks!

**Comment by misgeatgit** [comment]
ps. Its not working though. Am getting the following error

could not find http://schemeway.github.com/SchemeScript/update-site. I am using Luna.

**Comment by schemeway** [comment]
Sorry, I made a typo. It's github.io, not github.com in the update site URL. Fixed.

**Comment by misgeatgit** [comment]
All works fine now. Thanks!
